# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  # username: nppgbooking
  # password: 18i42eNPF57OGIjzbdkm
  username: postgres
  password: postgres
development:
  <<: *default
  database: app_development

production:
  <<: *default
  database: my_comp.production
test:
  <<: *default
  database: app_development